site_name: de_wiktio - German Wiktionary Parser
repo_url: https://github.com/lennon-c/de_wiktio
theme:
  name: "material"
  palette:
    primary: indigo

  features:
    - content.code.copy
    # - content.tabs.link
    - navigation.expand
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.footer
    - navigation.indexes
    - toc.follow
    - search.suggest
    - search.highlight
    - navigation.top
    # - toc.integrate
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/lennon-c


nav:
- Wiktionary Deutsch: README.md
- Usage: usage.md
- API:
  - API/index.md
  - entry: API/entry.md
  - fetch: API/fetch.md
  - settings: API/settings.md




plugins:
  - autorefs
  - search
  - open-in-new-tab: 
      add_icon: false
  - markdown-exec
  - mkdocstrings:
      handlers:
        python:
          import:
            - https://lxml.de/apidoc/objects.inv
            - https://docs.python.org/3/objects.inv
            - https://mwparserfromhell.readthedocs.io/en/latest/objects.inv
          options:
            allow_inspection: false
            show_root_heading: true
            inherited_members: true 
            members_order: source 
            show_if_no_docstring: true
            show_category_heading: true
            merge_init_into_class: true
            docstring_options:
              ignore_init_summary: true
            show_symbol_type_toc: true
            docstring_section_style: list # table # spacy 
            summary: true


watch:  
  - de_wiktio

extra_css: # some changes for mkdocstrings 
  - css/mkdocstrings.css

markdown_extensions:
- attr_list
- md_in_html 
- nl2br # obsidian callout
# - wikilinks
- admonition
- pymdownx.details
- pymdownx.superfences
- pymdownx.betterem
- pymdownx.tabbed:  
    alternate_style: true
- toc:
    title: On this page  
    permalink: true 
- pymdownx.emoji:
    emoji_index: !!python/name:material.extensions.emoji.twemoji
    emoji_generator: !!python/name:material.extensions.emoji.to_svg
- pymdownx.b64
- pymdownx.highlight:
    use_pygments: true
    pygments_lang_class: true
    # auto_title: true
    # linenums: true
    # anchor_linenums: true
    # linenums_style: pymdownx-inline 
- def_list
- pymdownx.tasklist:
    custom_checkbox: true 